apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-Deployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: prashantdey/travelmemory:fe
          ports:
            - containerPort: 3000