apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: backend
type: Opaque
data:
#connect to mongodb compass and create a database eg tm_k8s
#URL=mongodb://mongodb-service.database.svc.cluster.local:27017/tm_k8s used text to base64 converter
  MONGO_URI: bW9uZ29kYjovL21vbmdvZGItc2VydmljZS5kYXRhYmFzZS5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNy90bV9rOHM=
  

